# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
  desc "Distribute Android build to Firebase"
  lane :firebase_distribute do
    # Build app bundle or APK
    gradle(task: "assembleRelease")

    # Firebase App Distribution
    firebase_app_distribution(
      app: "1:211816411616:android:d886dd634725d9ee74fb85", 
      release_notes: "Đây là bản thử nghiệm mới.",
      groups: "D-SOFT",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      firebase_cli_token: "1//0eeigQpuzOS0GCgYIARAAGA4SNwF-L9IrpU4vD_jd4MIkz88l3HeqG3wJneOh_FKm43Ir3HLjZpzlPf4QoH8DUlyefKl9JAVyD74",
      debug: true
    )
  end
end
