name: Flutter CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Ensure assets directory exists
      run: mkdir -p assets

    - name: Create credentials.json
      run: echo "${{ secrets.CREDENTIALS_JSON }}" > assets/credentials.json

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Archive APK
      run: mv build/app/outputs/flutter-apk/app-release.apk app-release.apk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'release-${{ github.run_number }}-${{ github.sha }}'
        release_name: 'Release ${{ github.run_number }}'
        body: |
          This release includes the latest APK for the application.
        draft: false
        prerelease: false

    - name: Delete existing tag (if exists)
      run: |
        git tag -d release-${{ github.run_number }}-${{ github.sha }} || true
        git push origin :refs/tags/release-${{ github.run_number }}-${{ github.sha }} || true

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/apk
    - name: create Fastfile 
      run: echo "${{ secrets.FASTFILE }}" > android/Fastfile
      
    - name: Fastlane upload firebase distribute
      run: bundle exec fastlane firebase_distribute
